# Generated by Django 3.0.5 on 2020-04-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('acronym', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('objective', models.TextField()),
                ('rcn', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('programme', models.CharField(max_length=120)),
                ('topics', models.CharField(max_length=120)),
                ('frameworkProgramme', models.CharField(max_length=120)),
                ('startDate', models.CharField(max_length=120)),
                ('endDate', models.CharField(max_length=120)),
                ('projectUrl', models.CharField(max_length=120)),
                ('totalCost', models.IntegerField()),
                ('ecMaxContribution', models.IntegerField()),
                ('call', models.CharField(max_length=120)),
                ('fundingScheme', models.CharField(max_length=120)),
                ('coordinator', models.CharField(max_length=120)),
                ('coordinatorCountry', models.CharField(max_length=10)),
                ('participants', models.CharField(max_length=120)),
                ('participantCountries', models.CharField(max_length=120)),
            ],
        ),
    ]
