# Generated by Django 3.0.5 on 2020-04-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='call',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='coordinator',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='coordinatorCountry',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ecMaxContribution',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frameworkProgramme',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='fundingScheme',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='participantCountries',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='programme',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectUrl',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rcn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='topics',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='totalCost',
            field=models.IntegerField(null=True),
        ),
    ]
