# Generated by Django 3.0.5 on 2020-04-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0002_auto_20200417_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='acronym',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
