# Generated by Django 3.0.5 on 2020-04-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0003_math'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Math',
        ),
    ]
