# Generated by Django 3.0.5 on 2020-04-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0003_auto_20200417_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='objective',
            field=models.TextField(null=True),
        ),
    ]
