# Generated by Django 3.0.5 on 2020-04-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0004_auto_20200417_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='acronym',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='call',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frameworkProgramme',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='fundingScheme',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='participantCountries',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='programme',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectUrl',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='topics',
            field=models.TextField(null=True),
        ),
    ]
