# Generated by Django 3.0.5 on 2020-04-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0005_auto_20200417_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='coordinator',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='coordinatorCountry',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ecMaxContribution',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectUrl',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rcn',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='totalCost',
            field=models.TextField(null=True),
        ),
    ]
